# fly.toml app configuration file generated for location-mhd-auto on 2026-03-03T22:07:10Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'location-mhd-auto'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 2
  memory_mb = 1024
